package com.socodd.entities;
// Generated 21 juil. 2018 07:15:20 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Analyse generated by hbm2java
 */
@Entity
@Table(name = "analyse", catalog = "db_socodd")
public class Analyse implements java.io.Serializable {

	private Integer id;
	private String code;
	private int produit;
	private String nom;
	private String abrege;
	private int ordre;
	private float norme;
	private String formuleCalcul;
	private boolean ecranReception;
	private boolean ecranLot;
	private boolean etatReception;
	private boolean etatLot;

	public Analyse() {
	}

	public Analyse(String code, int produit, String nom, String abrege, int ordre, float norme, String formuleCalcul,
			boolean ecranReception, boolean ecranLot, boolean etatReception, boolean etatLot) {
		this.code = code;
		this.produit = produit;
		this.nom = nom;
		this.abrege = abrege;
		this.ordre = ordre;
		this.norme = norme;
		this.formuleCalcul = formuleCalcul;
		this.ecranReception = ecranReception;
		this.ecranLot = ecranLot;
		this.etatReception = etatReception;
		this.etatLot = etatLot;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "produit", nullable = false)
	public int getProduit() {
		return this.produit;
	}

	public void setProduit(int produit) {
		this.produit = produit;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "abrege", nullable = false, length = 50)
	public String getAbrege() {
		return this.abrege;
	}

	public void setAbrege(String abrege) {
		this.abrege = abrege;
	}

	@Column(name = "ordre", nullable = false)
	public int getOrdre() {
		return this.ordre;
	}

	public void setOrdre(int ordre) {
		this.ordre = ordre;
	}

	@Column(name = "norme", nullable = false, precision = 12, scale = 0)
	public float getNorme() {
		return this.norme;
	}

	public void setNorme(float norme) {
		this.norme = norme;
	}

	@Column(name = "formule_calcul", nullable = false, length = 100)
	public String getFormuleCalcul() {
		return this.formuleCalcul;
	}

	public void setFormuleCalcul(String formuleCalcul) {
		this.formuleCalcul = formuleCalcul;
	}

	@Column(name = "ecran_reception", nullable = false)
	public boolean isEcranReception() {
		return this.ecranReception;
	}

	public void setEcranReception(boolean ecranReception) {
		this.ecranReception = ecranReception;
	}

	@Column(name = "ecran_lot", nullable = false)
	public boolean isEcranLot() {
		return this.ecranLot;
	}

	public void setEcranLot(boolean ecranLot) {
		this.ecranLot = ecranLot;
	}

	@Column(name = "etat_reception", nullable = false)
	public boolean isEtatReception() {
		return this.etatReception;
	}

	public void setEtatReception(boolean etatReception) {
		this.etatReception = etatReception;
	}

	@Column(name = "etat_lot", nullable = false)
	public boolean isEtatLot() {
		return this.etatLot;
	}

	public void setEtatLot(boolean etatLot) {
		this.etatLot = etatLot;
	}

}
