package com.socodd.entities;
// Generated 7 sept. 2018 13:04:21 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "db_socodd")
public class Client implements java.io.Serializable {

	private Integer id;
	private TypeClient typeClient;
	private Banque banque;
	private String code;
	private String nom;
	private String adresse;
	private Date dateEntree;
	private String email;
	private String telephone;
	private String fax;
	private String numBic;
	private int numAgrement;
	private int numCc;
	private int numCompteTiers;
	private int numRccm;
	private int numBanque;
	private Set<ContratVente> contratVentes = new HashSet<ContratVente>(0);

	public Client() {
	}

	public Client(TypeClient typeClient, Banque banque, String code, String nom, String adresse, Date dateEntree,
			String email, String telephone, String fax, String numBic, int numAgrement, int numCc, int numCompteTiers,
			int numRccm, int numBanque) {
		this.typeClient = typeClient;
		this.banque = banque;
		this.code = code;
		this.nom = nom;
		this.adresse = adresse;
		this.dateEntree = dateEntree;
		this.email = email;
		this.telephone = telephone;
		this.fax = fax;
		this.numBic = numBic;
		this.numAgrement = numAgrement;
		this.numCc = numCc;
		this.numCompteTiers = numCompteTiers;
		this.numRccm = numRccm;
		this.numBanque = numBanque;
	}

	public Client(TypeClient typeClient, Banque banque, String code, String nom, String adresse, Date dateEntree,
			String email, String telephone, String fax, String numBic, int numAgrement, int numCc, int numCompteTiers,
			int numRccm, int numBanque, Set<ContratVente> contratVentes) {
		this.typeClient = typeClient;
		this.banque = banque;
		this.code = code;
		this.nom = nom;
		this.adresse = adresse;
		this.dateEntree = dateEntree;
		this.email = email;
		this.telephone = telephone;
		this.fax = fax;
		this.numBic = numBic;
		this.numAgrement = numAgrement;
		this.numCc = numCc;
		this.numCompteTiers = numCompteTiers;
		this.numRccm = numRccm;
		this.numBanque = numBanque;
		this.contratVentes = contratVentes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_client", nullable = false)
	public TypeClient getTypeClient() {
		return this.typeClient;
	}

	public void setTypeClient(TypeClient typeClient) {
		this.typeClient = typeClient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "banque", nullable = false)
	public Banque getBanque() {
		return this.banque;
	}

	public void setBanque(Banque banque) {
		this.banque = banque;
	}

	@Column(name = "code", nullable = false, length = 9)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "adresse", nullable = false, length = 65535)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_entree", nullable = false, length = 10)
	public Date getDateEntree() {
		return this.dateEntree;
	}

	public void setDateEntree(Date dateEntree) {
		this.dateEntree = dateEntree;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax", nullable = false, length = 10)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "num_bic", nullable = false, length = 50)
	public String getNumBic() {
		return this.numBic;
	}

	public void setNumBic(String numBic) {
		this.numBic = numBic;
	}

	@Column(name = "num_agrement", nullable = false)
	public int getNumAgrement() {
		return this.numAgrement;
	}

	public void setNumAgrement(int numAgrement) {
		this.numAgrement = numAgrement;
	}

	@Column(name = "num_cc", nullable = false)
	public int getNumCc() {
		return this.numCc;
	}

	public void setNumCc(int numCc) {
		this.numCc = numCc;
	}

	@Column(name = "num_compte_tiers", nullable = false)
	public int getNumCompteTiers() {
		return this.numCompteTiers;
	}

	public void setNumCompteTiers(int numCompteTiers) {
		this.numCompteTiers = numCompteTiers;
	}

	@Column(name = "num_rccm", nullable = false)
	public int getNumRccm() {
		return this.numRccm;
	}

	public void setNumRccm(int numRccm) {
		this.numRccm = numRccm;
	}

	@Column(name = "num_banque", nullable = false)
	public int getNumBanque() {
		return this.numBanque;
	}

	public void setNumBanque(int numBanque) {
		this.numBanque = numBanque;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<ContratVente> getContratVentes() {
		return this.contratVentes;
	}

	public void setContratVentes(Set<ContratVente> contratVentes) {
		this.contratVentes = contratVentes;
	}

}
