package com.socodd.entities;
// Generated 7 sept. 2018 13:04:21 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContratVente generated by hbm2java
 */
@Entity
@Table(name = "contrat_vente", catalog = "db_socodd")
public class ContratVente implements java.io.Serializable {

	private Integer id;
	private Devise devise;
	private Client client;
	private Produit produit;
	private String code;
	private String reference;
	private float poids;
	private float prixFixe;
	private float valeur;
	private Date dateVente;
	private float parite;
	private String decision;
	private float reste;

	public ContratVente() {
	}

	public ContratVente(Devise devise, Client client, Produit produit, String code, String reference, float poids,
			float prixFixe, float valeur, Date dateVente, float parite, String decision, float reste) {
		this.devise = devise;
		this.client = client;
		this.produit = produit;
		this.code = code;
		this.reference = reference;
		this.poids = poids;
		this.prixFixe = prixFixe;
		this.valeur = valeur;
		this.dateVente = dateVente;
		this.parite = parite;
		this.decision = decision;
		this.reste = reste;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "devise", nullable = false)
	public Devise getDevise() {
		return this.devise;
	}

	public void setDevise(Devise devise) {
		this.devise = devise;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "produit", nullable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "reference", nullable = false, length = 50)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "poids", nullable = false, precision = 12, scale = 0)
	public float getPoids() {
		return this.poids;
	}

	public void setPoids(float poids) {
		this.poids = poids;
	}

	@Column(name = "prix_fixe", nullable = false, precision = 12, scale = 0)
	public float getPrixFixe() {
		return this.prixFixe;
	}

	public void setPrixFixe(float prixFixe) {
		this.prixFixe = prixFixe;
	}

	@Column(name = "valeur", nullable = false, precision = 12, scale = 0)
	public float getValeur() {
		return this.valeur;
	}

	public void setValeur(float valeur) {
		this.valeur = valeur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_vente", nullable = false, length = 10)
	public Date getDateVente() {
		return this.dateVente;
	}

	public void setDateVente(Date dateVente) {
		this.dateVente = dateVente;
	}

	@Column(name = "parite", nullable = false, precision = 12, scale = 0)
	public float getParite() {
		return this.parite;
	}

	public void setParite(float parite) {
		this.parite = parite;
	}

	@Column(name = "decision", nullable = false, length = 50)
	public String getDecision() {
		return this.decision;
	}

	public void setDecision(String decision) {
		this.decision = decision;
	}

	@Column(name = "reste", nullable = false, precision = 12, scale = 0)
	public float getReste() {
		return this.reste;
	}

	public void setReste(float reste) {
		this.reste = reste;
	}

}
