package com.socodd.entities;
// Generated 25 août 2018 14:31:28 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "db_socodd")
public class Employee implements java.io.Serializable {

	private Integer id;
	private Departement departement;
	private Equipe equipe;
	private Nationalite nationalite;
	private Banque banque;
	private String code;
	private String matricule;
	private String nom;
	private Date dateNaissance;
	private String adresse;
	private Date dateEntree;
	private int numCompteTier;
	private String telephone;
	private String email;
	private String fonctionOccupee;
	private int numCompte;
	private Set<Equipe> equipes = new HashSet<Equipe>(0);

	public Employee() {
	}

	public Employee(Departement departement, Nationalite nationalite, Banque banque, String code, String matricule,
			String nom, Date dateNaissance, String adresse, Date dateEntree, int numCompteTier, String telephone,
			String email, String fonctionOccupee, int numCompte) {
		this.departement = departement;
		this.nationalite = nationalite;
		this.banque = banque;
		this.code = code;
		this.matricule = matricule;
		this.nom = nom;
		this.dateNaissance = dateNaissance;
		this.adresse = adresse;
		this.dateEntree = dateEntree;
		this.numCompteTier = numCompteTier;
		this.telephone = telephone;
		this.email = email;
		this.fonctionOccupee = fonctionOccupee;
		this.numCompte = numCompte;
	}

	public Employee(Departement departement, Equipe equipe, Nationalite nationalite, Banque banque, String code,
			String matricule, String nom, Date dateNaissance, String adresse, Date dateEntree, int numCompteTier,
			String telephone, String email, String fonctionOccupee, int numCompte, Set<Equipe> equipes) {
		this.departement = departement;
		this.equipe = equipe;
		this.nationalite = nationalite;
		this.banque = banque;
		this.code = code;
		this.matricule = matricule;
		this.nom = nom;
		this.dateNaissance = dateNaissance;
		this.adresse = adresse;
		this.dateEntree = dateEntree;
		this.numCompteTier = numCompteTier;
		this.telephone = telephone;
		this.email = email;
		this.fonctionOccupee = fonctionOccupee;
		this.numCompte = numCompte;
		this.equipes = equipes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departement", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipe")
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nationalite", nullable = false)
	public Nationalite getNationalite() {
		return this.nationalite;
	}

	public void setNationalite(Nationalite nationalite) {
		this.nationalite = nationalite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "banque", nullable = false)
	public Banque getBanque() {
		return this.banque;
	}

	public void setBanque(Banque banque) {
		this.banque = banque;
	}

	@Column(name = "code", nullable = false, length = 7)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "matricule", nullable = false, length = 10)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "nom", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissance", nullable = false, length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "adresse", nullable = false, length = 65535)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_entree", nullable = false, length = 10)
	public Date getDateEntree() {
		return this.dateEntree;
	}

	public void setDateEntree(Date dateEntree) {
		this.dateEntree = dateEntree;
	}

	@Column(name = "num_compte_tier", nullable = false)
	public int getNumCompteTier() {
		return this.numCompteTier;
	}

	public void setNumCompteTier(int numCompteTier) {
		this.numCompteTier = numCompteTier;
	}

	@Column(name = "telephone", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fonction_occupee", nullable = false, length = 10)
	public String getFonctionOccupee() {
		return this.fonctionOccupee;
	}

	public void setFonctionOccupee(String fonctionOccupee) {
		this.fonctionOccupee = fonctionOccupee;
	}

	@Column(name = "num_compte", nullable = false)
	public int getNumCompte() {
		return this.numCompte;
	}

	public void setNumCompte(int numCompte) {
		this.numCompte = numCompte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Equipe> getEquipes() {
		return this.equipes;
	}

	public void setEquipes(Set<Equipe> equipes) {
		this.equipes = equipes;
	}

}
