package com.socodd.entities;
// Generated 21 juil. 2018 07:15:20 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "db_socodd")
public class Employee implements java.io.Serializable {

	private Integer id;
	private Nationalite nationalite;
	private int code;
	private String matricule;
	private String nom;
	private Date dateNaissance;
	private String adresse;
	private Date dateEntree;
	private int numCompteTier;
	private String telephone;
	private String email;
	private int departement;
	private String fonctionOccupee;
	private int equipe;
	private String banque;
	private int numCompte;

	public Employee() {
	}

	public Employee(Nationalite nationalite, int code, String matricule, String nom, Date dateNaissance, String adresse,
			Date dateEntree, int numCompteTier, String telephone, String email, int departement, String fonctionOccupee,
			int equipe, String banque, int numCompte) {
		this.nationalite = nationalite;
		this.code = code;
		this.matricule = matricule;
		this.nom = nom;
		this.dateNaissance = dateNaissance;
		this.adresse = adresse;
		this.dateEntree = dateEntree;
		this.numCompteTier = numCompteTier;
		this.telephone = telephone;
		this.email = email;
		this.departement = departement;
		this.fonctionOccupee = fonctionOccupee;
		this.equipe = equipe;
		this.banque = banque;
		this.numCompte = numCompte;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nationalite", nullable = false)
	public Nationalite getNationalite() {
		return this.nationalite;
	}

	public void setNationalite(Nationalite nationalite) {
		this.nationalite = nationalite;
	}

	@Column(name = "code", nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@Column(name = "matricule", nullable = false, length = 10)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "nom", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissance", nullable = false, length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "adresse", nullable = false, length = 65535)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_entree", nullable = false, length = 10)
	public Date getDateEntree() {
		return this.dateEntree;
	}

	public void setDateEntree(Date dateEntree) {
		this.dateEntree = dateEntree;
	}

	@Column(name = "num_compte_tier", nullable = false)
	public int getNumCompteTier() {
		return this.numCompteTier;
	}

	public void setNumCompteTier(int numCompteTier) {
		this.numCompteTier = numCompteTier;
	}

	@Column(name = "telephone", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "departement", nullable = false)
	public int getDepartement() {
		return this.departement;
	}

	public void setDepartement(int departement) {
		this.departement = departement;
	}

	@Column(name = "fonction_occupee", nullable = false, length = 10)
	public String getFonctionOccupee() {
		return this.fonctionOccupee;
	}

	public void setFonctionOccupee(String fonctionOccupee) {
		this.fonctionOccupee = fonctionOccupee;
	}

	@Column(name = "equipe", nullable = false)
	public int getEquipe() {
		return this.equipe;
	}

	public void setEquipe(int equipe) {
		this.equipe = equipe;
	}

	@Column(name = "banque", nullable = false, length = 50)
	public String getBanque() {
		return this.banque;
	}

	public void setBanque(String banque) {
		this.banque = banque;
	}

	@Column(name = "num_compte", nullable = false)
	public int getNumCompte() {
		return this.numCompte;
	}

	public void setNumCompte(int numCompte) {
		this.numCompte = numCompte;
	}

}
