package com.socodd.entities;
// Generated 7 sept. 2018 13:04:21 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FabricationLots generated by hbm2java
 */
@Entity
@Table(name = "fabrication_lots", catalog = "db_socodd")
public class FabricationLots implements java.io.Serializable {

	private Integer id;
	private Magasin magasin;
	private Usine usine;
	private Produit produit;
	private String code;
	private Date date;

	public FabricationLots() {
	}

	public FabricationLots(Magasin magasin, Usine usine, Produit produit, String code, Date date) {
		this.magasin = magasin;
		this.usine = usine;
		this.produit = produit;
		this.code = code;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "magasin", nullable = false)
	public Magasin getMagasin() {
		return this.magasin;
	}

	public void setMagasin(Magasin magasin) {
		this.magasin = magasin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usine", nullable = false)
	public Usine getUsine() {
		return this.usine;
	}

	public void setUsine(Usine usine) {
		this.usine = usine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "produit", nullable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "code", nullable = false, length = 7)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
