package com.socodd.entities;
// Generated 10 août 2018 09:27:06 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name = "fournisseur", catalog = "db_socodd")
public class Fournisseur implements java.io.Serializable {

	private Integer id;
	private TypeFournisseur typeFournisseur;
	private String code;
	private String nom;
	private String adresse;
	private Date dateEntree;
	private String telephone;
	private String fax;
	private String email;
	private int numCompteTiers;
	private int numCc;
	private int numRccm;
	private int numAgrement;
	private String numBic;
	private String banque;
	private int numBanque;

	public Fournisseur() {
	}

	public Fournisseur(TypeFournisseur typeFournisseur, String code, String nom, String adresse, Date dateEntree,
			String telephone, String fax, String email, int numCompteTiers, int numCc, int numRccm, int numAgrement,
			String numBic, String banque, int numBanque) {
		this.typeFournisseur = typeFournisseur;
		this.code = code;
		this.nom = nom;
		this.adresse = adresse;
		this.dateEntree = dateEntree;
		this.telephone = telephone;
		this.fax = fax;
		this.email = email;
		this.numCompteTiers = numCompteTiers;
		this.numCc = numCc;
		this.numRccm = numRccm;
		this.numAgrement = numAgrement;
		this.numBic = numBic;
		this.banque = banque;
		this.numBanque = numBanque;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_fournisseur", nullable = false)
	public TypeFournisseur getTypeFournisseur() {
		return this.typeFournisseur;
	}

	public void setTypeFournisseur(TypeFournisseur typeFournisseur) {
		this.typeFournisseur = typeFournisseur;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "adresse", nullable = false, length = 65535)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_entree", nullable = false, length = 10)
	public Date getDateEntree() {
		return this.dateEntree;
	}

	public void setDateEntree(Date dateEntree) {
		this.dateEntree = dateEntree;
	}

	@Column(name = "telephone", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax", nullable = false, length = 10)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "num_compte_tiers", nullable = false)
	public int getNumCompteTiers() {
		return this.numCompteTiers;
	}

	public void setNumCompteTiers(int numCompteTiers) {
		this.numCompteTiers = numCompteTiers;
	}

	@Column(name = "num_cc", nullable = false)
	public int getNumCc() {
		return this.numCc;
	}

	public void setNumCc(int numCc) {
		this.numCc = numCc;
	}

	@Column(name = "num_rccm", nullable = false)
	public int getNumRccm() {
		return this.numRccm;
	}

	public void setNumRccm(int numRccm) {
		this.numRccm = numRccm;
	}

	@Column(name = "num_agrement", nullable = false)
	public int getNumAgrement() {
		return this.numAgrement;
	}

	public void setNumAgrement(int numAgrement) {
		this.numAgrement = numAgrement;
	}

	@Column(name = "num_bic", nullable = false)
	public String getNumBic() {
		return this.numBic;
	}

	public void setNumBic(String numBic) {
		this.numBic = numBic;
	}

	@Column(name = "banque", nullable = false, length = 50)
	public String getBanque() {
		return this.banque;
	}

	public void setBanque(String banque) {
		this.banque = banque;
	}

	@Column(name = "num_banque", nullable = false)
	public int getNumBanque() {
		return this.numBanque;
	}

	public void setNumBanque(int numBanque) {
		this.numBanque = numBanque;
	}

}
