package com.socodd.entities;
// Generated 30 juil. 2018 14:57:08 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name = "fournisseur", catalog = "db_socodd")
public class Fournisseur implements java.io.Serializable {

	private Integer id;
	private TypeFournisseur typeFournisseur;
	private String code;
	private String nom;
	private String adresse;
	private Date dateEntree;
	private String telephone;
	private String fax;
	private String email;
	private int numCompteTiers;
	private Set<ContratAchat> contratAchats = new HashSet<ContratAchat>(0);

	public Fournisseur() {
	}

	public Fournisseur(TypeFournisseur typeFournisseur, String code, String nom, String adresse, Date dateEntree,
			String telephone, String fax, String email, int numCompteTiers) {
		this.typeFournisseur = typeFournisseur;
		this.code = code;
		this.nom = nom;
		this.adresse = adresse;
		this.dateEntree = dateEntree;
		this.telephone = telephone;
		this.fax = fax;
		this.email = email;
		this.numCompteTiers = numCompteTiers;
	}

	public Fournisseur(TypeFournisseur typeFournisseur, String code, String nom, String adresse, Date dateEntree,
			String telephone, String fax, String email, int numCompteTiers, Set<ContratAchat> contratAchats) {
		this.typeFournisseur = typeFournisseur;
		this.code = code;
		this.nom = nom;
		this.adresse = adresse;
		this.dateEntree = dateEntree;
		this.telephone = telephone;
		this.fax = fax;
		this.email = email;
		this.numCompteTiers = numCompteTiers;
		this.contratAchats = contratAchats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_fournisseur", nullable = false)
	public TypeFournisseur getTypeFournisseur() {
		return this.typeFournisseur;
	}

	public void setTypeFournisseur(TypeFournisseur typeFournisseur) {
		this.typeFournisseur = typeFournisseur;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "adresse", nullable = false, length = 65535)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_entree", nullable = false, length = 10)
	public Date getDateEntree() {
		return this.dateEntree;
	}

	public void setDateEntree(Date dateEntree) {
		this.dateEntree = dateEntree;
	}

	@Column(name = "telephone", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax", nullable = false, length = 10)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "num_compte_tiers", nullable = false)
	public int getNumCompteTiers() {
		return this.numCompteTiers;
	}

	public void setNumCompteTiers(int numCompteTiers) {
		this.numCompteTiers = numCompteTiers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fournisseur")
	public Set<ContratAchat> getContratAchats() {
		return this.contratAchats;
	}

	public void setContratAchats(Set<ContratAchat> contratAchats) {
		this.contratAchats = contratAchats;
	}

}
