package com.socodd.entities;
// Generated 30 juil. 2018 14:57:08 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Magasin generated by hbm2java
 */
@Entity
@Table(name = "magasin", catalog = "db_socodd")
public class Magasin implements java.io.Serializable {

	private Integer id;
	private Localite localite;
	private String code;
	private int nom;
	private Set<FabricationLots> fabricationLotses = new HashSet<FabricationLots>(0);

	public Magasin() {
	}

	public Magasin(Localite localite, String code, int nom) {
		this.localite = localite;
		this.code = code;
		this.nom = nom;
	}

	public Magasin(Localite localite, String code, int nom, Set<FabricationLots> fabricationLotses) {
		this.localite = localite;
		this.code = code;
		this.nom = nom;
		this.fabricationLotses = fabricationLotses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "localite", nullable = false)
	public Localite getLocalite() {
		return this.localite;
	}

	public void setLocalite(Localite localite) {
		this.localite = localite;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false)
	public int getNom() {
		return this.nom;
	}

	public void setNom(int nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "magasin")
	public Set<FabricationLots> getFabricationLotses() {
		return this.fabricationLotses;
	}

	public void setFabricationLotses(Set<FabricationLots> fabricationLotses) {
		this.fabricationLotses = fabricationLotses;
	}

}
