package com.socodd.entities;
// Generated 7 sept. 2018 13:04:21 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParcAuto generated by hbm2java
 */
@Entity
@Table(name = "parc_auto", catalog = "db_socodd")
public class ParcAuto implements java.io.Serializable {

	private int id;
	private TypeParcAuto typeParcAuto;
	private String code;
	private String immatriculation;
	private String nom;
	private Date dateEntree;
	private float capaciteReservoire;
	private float conso;
	private float poidsBrut;
	private float tare;
	private Date dateExpVisiteTech;
	private Date dateExpAssurance;
	private Date dateExpPatente;
	private Date dateExpVignette;
	private Set<ReceptionProduits> receptionProduitses = new HashSet<ReceptionProduits>(0);

	public ParcAuto() {
	}

	public ParcAuto(int id, TypeParcAuto typeParcAuto, String code, String immatriculation, String nom, Date dateEntree,
			float capaciteReservoire, float conso, float poidsBrut, float tare, Date dateExpVisiteTech,
			Date dateExpAssurance, Date dateExpPatente, Date dateExpVignette) {
		this.id = id;
		this.typeParcAuto = typeParcAuto;
		this.code = code;
		this.immatriculation = immatriculation;
		this.nom = nom;
		this.dateEntree = dateEntree;
		this.capaciteReservoire = capaciteReservoire;
		this.conso = conso;
		this.poidsBrut = poidsBrut;
		this.tare = tare;
		this.dateExpVisiteTech = dateExpVisiteTech;
		this.dateExpAssurance = dateExpAssurance;
		this.dateExpPatente = dateExpPatente;
		this.dateExpVignette = dateExpVignette;
	}

	public ParcAuto(int id, TypeParcAuto typeParcAuto, String code, String immatriculation, String nom, Date dateEntree,
			float capaciteReservoire, float conso, float poidsBrut, float tare, Date dateExpVisiteTech,
			Date dateExpAssurance, Date dateExpPatente, Date dateExpVignette,
			Set<ReceptionProduits> receptionProduitses) {
		this.id = id;
		this.typeParcAuto = typeParcAuto;
		this.code = code;
		this.immatriculation = immatriculation;
		this.nom = nom;
		this.dateEntree = dateEntree;
		this.capaciteReservoire = capaciteReservoire;
		this.conso = conso;
		this.poidsBrut = poidsBrut;
		this.tare = tare;
		this.dateExpVisiteTech = dateExpVisiteTech;
		this.dateExpAssurance = dateExpAssurance;
		this.dateExpPatente = dateExpPatente;
		this.dateExpVignette = dateExpVignette;
		this.receptionProduitses = receptionProduitses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_parc_auto", nullable = false)
	public TypeParcAuto getTypeParcAuto() {
		return this.typeParcAuto;
	}

	public void setTypeParcAuto(TypeParcAuto typeParcAuto) {
		this.typeParcAuto = typeParcAuto;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "immatriculation", nullable = false, length = 50)
	public String getImmatriculation() {
		return this.immatriculation;
	}

	public void setImmatriculation(String immatriculation) {
		this.immatriculation = immatriculation;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_entree", nullable = false, length = 10)
	public Date getDateEntree() {
		return this.dateEntree;
	}

	public void setDateEntree(Date dateEntree) {
		this.dateEntree = dateEntree;
	}

	@Column(name = "capacite_reservoire", nullable = false, precision = 12, scale = 0)
	public float getCapaciteReservoire() {
		return this.capaciteReservoire;
	}

	public void setCapaciteReservoire(float capaciteReservoire) {
		this.capaciteReservoire = capaciteReservoire;
	}

	@Column(name = "conso", nullable = false, precision = 12, scale = 0)
	public float getConso() {
		return this.conso;
	}

	public void setConso(float conso) {
		this.conso = conso;
	}

	@Column(name = "poids_brut", nullable = false, precision = 12, scale = 0)
	public float getPoidsBrut() {
		return this.poidsBrut;
	}

	public void setPoidsBrut(float poidsBrut) {
		this.poidsBrut = poidsBrut;
	}

	@Column(name = "tare", nullable = false, precision = 12, scale = 0)
	public float getTare() {
		return this.tare;
	}

	public void setTare(float tare) {
		this.tare = tare;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_exp_visite_tech", nullable = false, length = 10)
	public Date getDateExpVisiteTech() {
		return this.dateExpVisiteTech;
	}

	public void setDateExpVisiteTech(Date dateExpVisiteTech) {
		this.dateExpVisiteTech = dateExpVisiteTech;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_exp_assurance", nullable = false, length = 10)
	public Date getDateExpAssurance() {
		return this.dateExpAssurance;
	}

	public void setDateExpAssurance(Date dateExpAssurance) {
		this.dateExpAssurance = dateExpAssurance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_exp_patente", nullable = false, length = 10)
	public Date getDateExpPatente() {
		return this.dateExpPatente;
	}

	public void setDateExpPatente(Date dateExpPatente) {
		this.dateExpPatente = dateExpPatente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_exp_vignette", nullable = false, length = 10)
	public Date getDateExpVignette() {
		return this.dateExpVignette;
	}

	public void setDateExpVignette(Date dateExpVignette) {
		this.dateExpVignette = dateExpVignette;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcAuto")
	public Set<ReceptionProduits> getReceptionProduitses() {
		return this.receptionProduitses;
	}

	public void setReceptionProduitses(Set<ReceptionProduits> receptionProduitses) {
		this.receptionProduitses = receptionProduitses;
	}

}
