package com.socodd.entities;
// Generated 30 juil. 2018 14:57:08 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "db_socodd")
public class Produit implements java.io.Serializable {

	private Integer id;
	private String code;
	private String nom;
	private int titreCompagne;
	private int sacBrousse;
	private int sacExport;
	private int prefNumBE;
	private int prochainAchatNum;
	private int cpteAchat;
	private float tauxAchatBic;
	private int prefNumBS;
	private int prochainVenteNum;
	private int cpteVte;
	private int cpteVenteBic;
	private float prixAchatIndicatif;
	private float prixVenteIndicatif;
	private float fraisTransport;
	private int mntDeboursTransit;
	private float tauxDeboursTransit;
	private int prefixeNumCdc;
	private int poidsTherorique;
	private Set<ContratAchat> contratAchats = new HashSet<ContratAchat>(0);
	private Set<Analyse> analyses = new HashSet<Analyse>(0);
	private Set<ReceptionProduits> receptionProduitses = new HashSet<ReceptionProduits>(0);
	private Set<Variete> varietes = new HashSet<Variete>(0);
	private Set<Marque> marques = new HashSet<Marque>(0);
	private Set<Qualite> qualites = new HashSet<Qualite>(0);
	private Set<ItemsDebours> itemsDebourses = new HashSet<ItemsDebours>(0);
	private Set<FabricationLots> fabricationLotses = new HashSet<FabricationLots>(0);

	public Produit() {
	}

	public Produit(String code, String nom, int titreCompagne, int sacBrousse, int sacExport, int prefNumBE,
			int prochainAchatNum, int cpteAchat, float tauxAchatBic, int prefNumBS, int prochainVenteNum, int cpteVte,
			int cpteVenteBic, float prixAchatIndicatif, float prixVenteIndicatif, float fraisTransport,
			int mntDeboursTransit, float tauxDeboursTransit, int prefixeNumCdc, int poidsTherorique) {
		this.code = code;
		this.nom = nom;
		this.titreCompagne = titreCompagne;
		this.sacBrousse = sacBrousse;
		this.sacExport = sacExport;
		this.prefNumBE = prefNumBE;
		this.prochainAchatNum = prochainAchatNum;
		this.cpteAchat = cpteAchat;
		this.tauxAchatBic = tauxAchatBic;
		this.prefNumBS = prefNumBS;
		this.prochainVenteNum = prochainVenteNum;
		this.cpteVte = cpteVte;
		this.cpteVenteBic = cpteVenteBic;
		this.prixAchatIndicatif = prixAchatIndicatif;
		this.prixVenteIndicatif = prixVenteIndicatif;
		this.fraisTransport = fraisTransport;
		this.mntDeboursTransit = mntDeboursTransit;
		this.tauxDeboursTransit = tauxDeboursTransit;
		this.prefixeNumCdc = prefixeNumCdc;
		this.poidsTherorique = poidsTherorique;
	}

	public Produit(String code, String nom, int titreCompagne, int sacBrousse, int sacExport, int prefNumBE,
			int prochainAchatNum, int cpteAchat, float tauxAchatBic, int prefNumBS, int prochainVenteNum, int cpteVte,
			int cpteVenteBic, float prixAchatIndicatif, float prixVenteIndicatif, float fraisTransport,
			int mntDeboursTransit, float tauxDeboursTransit, int prefixeNumCdc, int poidsTherorique,
			Set<ContratAchat> contratAchats, Set<Analyse> analyses, Set<ReceptionProduits> receptionProduitses,
			Set<Variete> varietes, Set<Marque> marques, Set<Qualite> qualites, Set<ItemsDebours> itemsDebourses,
			Set<FabricationLots> fabricationLotses) {
		this.code = code;
		this.nom = nom;
		this.titreCompagne = titreCompagne;
		this.sacBrousse = sacBrousse;
		this.sacExport = sacExport;
		this.prefNumBE = prefNumBE;
		this.prochainAchatNum = prochainAchatNum;
		this.cpteAchat = cpteAchat;
		this.tauxAchatBic = tauxAchatBic;
		this.prefNumBS = prefNumBS;
		this.prochainVenteNum = prochainVenteNum;
		this.cpteVte = cpteVte;
		this.cpteVenteBic = cpteVenteBic;
		this.prixAchatIndicatif = prixAchatIndicatif;
		this.prixVenteIndicatif = prixVenteIndicatif;
		this.fraisTransport = fraisTransport;
		this.mntDeboursTransit = mntDeboursTransit;
		this.tauxDeboursTransit = tauxDeboursTransit;
		this.prefixeNumCdc = prefixeNumCdc;
		this.poidsTherorique = poidsTherorique;
		this.contratAchats = contratAchats;
		this.analyses = analyses;
		this.receptionProduitses = receptionProduitses;
		this.varietes = varietes;
		this.marques = marques;
		this.qualites = qualites;
		this.itemsDebourses = itemsDebourses;
		this.fabricationLotses = fabricationLotses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "titre_compagne", nullable = false)
	public int getTitreCompagne() {
		return this.titreCompagne;
	}

	public void setTitreCompagne(int titreCompagne) {
		this.titreCompagne = titreCompagne;
	}

	@Column(name = "sac_brousse", nullable = false)
	public int getSacBrousse() {
		return this.sacBrousse;
	}

	public void setSacBrousse(int sacBrousse) {
		this.sacBrousse = sacBrousse;
	}

	@Column(name = "sac_export", nullable = false)
	public int getSacExport() {
		return this.sacExport;
	}

	public void setSacExport(int sacExport) {
		this.sacExport = sacExport;
	}

	@Column(name = "pref_num_b_e", nullable = false)
	public int getPrefNumBE() {
		return this.prefNumBE;
	}

	public void setPrefNumBE(int prefNumBE) {
		this.prefNumBE = prefNumBE;
	}

	@Column(name = "prochain_achat_num", nullable = false)
	public int getProchainAchatNum() {
		return this.prochainAchatNum;
	}

	public void setProchainAchatNum(int prochainAchatNum) {
		this.prochainAchatNum = prochainAchatNum;
	}

	@Column(name = "cpte_achat", nullable = false)
	public int getCpteAchat() {
		return this.cpteAchat;
	}

	public void setCpteAchat(int cpteAchat) {
		this.cpteAchat = cpteAchat;
	}

	@Column(name = "taux_achat_bic", nullable = false, precision = 12, scale = 0)
	public float getTauxAchatBic() {
		return this.tauxAchatBic;
	}

	public void setTauxAchatBic(float tauxAchatBic) {
		this.tauxAchatBic = tauxAchatBic;
	}

	@Column(name = "pref_num_b_s", nullable = false)
	public int getPrefNumBS() {
		return this.prefNumBS;
	}

	public void setPrefNumBS(int prefNumBS) {
		this.prefNumBS = prefNumBS;
	}

	@Column(name = "prochain_vente_num", nullable = false)
	public int getProchainVenteNum() {
		return this.prochainVenteNum;
	}

	public void setProchainVenteNum(int prochainVenteNum) {
		this.prochainVenteNum = prochainVenteNum;
	}

	@Column(name = "cpte_vte", nullable = false)
	public int getCpteVte() {
		return this.cpteVte;
	}

	public void setCpteVte(int cpteVte) {
		this.cpteVte = cpteVte;
	}

	@Column(name = "cpte_vente_bic", nullable = false)
	public int getCpteVenteBic() {
		return this.cpteVenteBic;
	}

	public void setCpteVenteBic(int cpteVenteBic) {
		this.cpteVenteBic = cpteVenteBic;
	}

	@Column(name = "prix_achat_indicatif", nullable = false, precision = 12, scale = 0)
	public float getPrixAchatIndicatif() {
		return this.prixAchatIndicatif;
	}

	public void setPrixAchatIndicatif(float prixAchatIndicatif) {
		this.prixAchatIndicatif = prixAchatIndicatif;
	}

	@Column(name = "prix_vente_indicatif", nullable = false, precision = 12, scale = 0)
	public float getPrixVenteIndicatif() {
		return this.prixVenteIndicatif;
	}

	public void setPrixVenteIndicatif(float prixVenteIndicatif) {
		this.prixVenteIndicatif = prixVenteIndicatif;
	}

	@Column(name = "frais_transport", nullable = false, precision = 12, scale = 0)
	public float getFraisTransport() {
		return this.fraisTransport;
	}

	public void setFraisTransport(float fraisTransport) {
		this.fraisTransport = fraisTransport;
	}

	@Column(name = "mnt_debours_transit", nullable = false)
	public int getMntDeboursTransit() {
		return this.mntDeboursTransit;
	}

	public void setMntDeboursTransit(int mntDeboursTransit) {
		this.mntDeboursTransit = mntDeboursTransit;
	}

	@Column(name = "taux_debours_transit", nullable = false, precision = 12, scale = 0)
	public float getTauxDeboursTransit() {
		return this.tauxDeboursTransit;
	}

	public void setTauxDeboursTransit(float tauxDeboursTransit) {
		this.tauxDeboursTransit = tauxDeboursTransit;
	}

	@Column(name = "prefixe_num_cdc", nullable = false)
	public int getPrefixeNumCdc() {
		return this.prefixeNumCdc;
	}

	public void setPrefixeNumCdc(int prefixeNumCdc) {
		this.prefixeNumCdc = prefixeNumCdc;
	}

	@Column(name = "poids_therorique", nullable = false)
	public int getPoidsTherorique() {
		return this.poidsTherorique;
	}

	public void setPoidsTherorique(int poidsTherorique) {
		this.poidsTherorique = poidsTherorique;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<ContratAchat> getContratAchats() {
		return this.contratAchats;
	}

	public void setContratAchats(Set<ContratAchat> contratAchats) {
		this.contratAchats = contratAchats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Analyse> getAnalyses() {
		return this.analyses;
	}

	public void setAnalyses(Set<Analyse> analyses) {
		this.analyses = analyses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<ReceptionProduits> getReceptionProduitses() {
		return this.receptionProduitses;
	}

	public void setReceptionProduitses(Set<ReceptionProduits> receptionProduitses) {
		this.receptionProduitses = receptionProduitses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Variete> getVarietes() {
		return this.varietes;
	}

	public void setVarietes(Set<Variete> varietes) {
		this.varietes = varietes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Marque> getMarques() {
		return this.marques;
	}

	public void setMarques(Set<Marque> marques) {
		this.marques = marques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Qualite> getQualites() {
		return this.qualites;
	}

	public void setQualites(Set<Qualite> qualites) {
		this.qualites = qualites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<ItemsDebours> getItemsDebourses() {
		return this.itemsDebourses;
	}

	public void setItemsDebourses(Set<ItemsDebours> itemsDebourses) {
		this.itemsDebourses = itemsDebourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<FabricationLots> getFabricationLotses() {
		return this.fabricationLotses;
	}

	public void setFabricationLotses(Set<FabricationLots> fabricationLotses) {
		this.fabricationLotses = fabricationLotses;
	}

}
