package com.socodd.entities;
// Generated 25 août 2018 14:31:28 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "db_socodd")
public class Produit implements java.io.Serializable {

	private Integer id;
	private TypeSac typeSacBySacBrousse;
	private TypeSac typeSacBySacExport;
	private String code;
	private String nom;
	private String titreCompagne;
	private Integer prefNumBE;
	private Integer prochainAchatNum;
	private Integer cpteAchat;
	private Float tauxAchatBic;
	private Integer prefNumBS;
	private Integer prochainVenteNum;
	private Integer cpteVte;
	private Integer cpteVenteBic;
	private Float prixAchatIndicatif;
	private Float prixVenteIndicatif;
	private Float fraisTransport;
	private Integer mntDeboursTransit;
	private Float tauxDeboursTransit;
	private Integer prefixeNumCdc;
	private Integer poidsTheorique;
	private Set<ContratAchat> contratAchats = new HashSet<ContratAchat>(0);
	private Set<Analyse> analyses = new HashSet<Analyse>(0);
	private Set<ReceptionProduits> receptionProduitses = new HashSet<ReceptionProduits>(0);
	private Set<ContratVente> contratVentes = new HashSet<ContratVente>(0);
	private Set<Variete> varietes = new HashSet<Variete>(0);
	private Set<Marque> marques = new HashSet<Marque>(0);
	private Set<Qualite> qualites = new HashSet<Qualite>(0);
	private Set<ItemsDebours> itemsDebourses = new HashSet<ItemsDebours>(0);
	private Set<FabricationLots> fabricationLotses = new HashSet<FabricationLots>(0);

	public Produit() {
	}

	public Produit(TypeSac typeSacBySacBrousse, TypeSac typeSacBySacExport, String code, String nom,
			String titreCompagne, Integer prefNumBE, Integer prochainAchatNum, Integer cpteAchat, Float tauxAchatBic,
			Integer prefNumBS, Integer prochainVenteNum, Integer cpteVte, Integer cpteVenteBic,
			Float prixAchatIndicatif, Float prixVenteIndicatif, Float fraisTransport, Integer mntDeboursTransit,
			Float tauxDeboursTransit, Integer prefixeNumCdc, Integer poidsTheorique, Set<ContratAchat> contratAchats,
			Set<Analyse> analyses, Set<ReceptionProduits> receptionProduitses, Set<ContratVente> contratVentes,
			Set<Variete> varietes, Set<Marque> marques, Set<Qualite> qualites, Set<ItemsDebours> itemsDebourses,
			Set<FabricationLots> fabricationLotses) {
		this.typeSacBySacBrousse = typeSacBySacBrousse;
		this.typeSacBySacExport = typeSacBySacExport;
		this.code = code;
		this.nom = nom;
		this.titreCompagne = titreCompagne;
		this.prefNumBE = prefNumBE;
		this.prochainAchatNum = prochainAchatNum;
		this.cpteAchat = cpteAchat;
		this.tauxAchatBic = tauxAchatBic;
		this.prefNumBS = prefNumBS;
		this.prochainVenteNum = prochainVenteNum;
		this.cpteVte = cpteVte;
		this.cpteVenteBic = cpteVenteBic;
		this.prixAchatIndicatif = prixAchatIndicatif;
		this.prixVenteIndicatif = prixVenteIndicatif;
		this.fraisTransport = fraisTransport;
		this.mntDeboursTransit = mntDeboursTransit;
		this.tauxDeboursTransit = tauxDeboursTransit;
		this.prefixeNumCdc = prefixeNumCdc;
		this.poidsTheorique = poidsTheorique;
		this.contratAchats = contratAchats;
		this.analyses = analyses;
		this.receptionProduitses = receptionProduitses;
		this.contratVentes = contratVentes;
		this.varietes = varietes;
		this.marques = marques;
		this.qualites = qualites;
		this.itemsDebourses = itemsDebourses;
		this.fabricationLotses = fabricationLotses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sac_brousse")
	public TypeSac getTypeSacBySacBrousse() {
		return this.typeSacBySacBrousse;
	}

	public void setTypeSacBySacBrousse(TypeSac typeSacBySacBrousse) {
		this.typeSacBySacBrousse = typeSacBySacBrousse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sac_export")
	public TypeSac getTypeSacBySacExport() {
		return this.typeSacBySacExport;
	}

	public void setTypeSacBySacExport(TypeSac typeSacBySacExport) {
		this.typeSacBySacExport = typeSacBySacExport;
	}

	@Column(name = "code", length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "titre_compagne", length = 50)
	public String getTitreCompagne() {
		return this.titreCompagne;
	}

	public void setTitreCompagne(String titreCompagne) {
		this.titreCompagne = titreCompagne;
	}

	@Column(name = "pref_num_b_e")
	public Integer getPrefNumBE() {
		return this.prefNumBE;
	}

	public void setPrefNumBE(Integer prefNumBE) {
		this.prefNumBE = prefNumBE;
	}

	@Column(name = "prochain_achat_num")
	public Integer getProchainAchatNum() {
		return this.prochainAchatNum;
	}

	public void setProchainAchatNum(Integer prochainAchatNum) {
		this.prochainAchatNum = prochainAchatNum;
	}

	@Column(name = "cpte_achat")
	public Integer getCpteAchat() {
		return this.cpteAchat;
	}

	public void setCpteAchat(Integer cpteAchat) {
		this.cpteAchat = cpteAchat;
	}

	@Column(name = "taux_achat_bic", precision = 12, scale = 0)
	public Float getTauxAchatBic() {
		return this.tauxAchatBic;
	}

	public void setTauxAchatBic(Float tauxAchatBic) {
		this.tauxAchatBic = tauxAchatBic;
	}

	@Column(name = "pref_num_b_s")
	public Integer getPrefNumBS() {
		return this.prefNumBS;
	}

	public void setPrefNumBS(Integer prefNumBS) {
		this.prefNumBS = prefNumBS;
	}

	@Column(name = "prochain_vente_num")
	public Integer getProchainVenteNum() {
		return this.prochainVenteNum;
	}

	public void setProchainVenteNum(Integer prochainVenteNum) {
		this.prochainVenteNum = prochainVenteNum;
	}

	@Column(name = "cpte_vte")
	public Integer getCpteVte() {
		return this.cpteVte;
	}

	public void setCpteVte(Integer cpteVte) {
		this.cpteVte = cpteVte;
	}

	@Column(name = "cpte_vente_bic")
	public Integer getCpteVenteBic() {
		return this.cpteVenteBic;
	}

	public void setCpteVenteBic(Integer cpteVenteBic) {
		this.cpteVenteBic = cpteVenteBic;
	}

	@Column(name = "prix_achat_indicatif", precision = 12, scale = 0)
	public Float getPrixAchatIndicatif() {
		return this.prixAchatIndicatif;
	}

	public void setPrixAchatIndicatif(Float prixAchatIndicatif) {
		this.prixAchatIndicatif = prixAchatIndicatif;
	}

	@Column(name = "prix_vente_indicatif", precision = 12, scale = 0)
	public Float getPrixVenteIndicatif() {
		return this.prixVenteIndicatif;
	}

	public void setPrixVenteIndicatif(Float prixVenteIndicatif) {
		this.prixVenteIndicatif = prixVenteIndicatif;
	}

	@Column(name = "frais_transport", precision = 12, scale = 0)
	public Float getFraisTransport() {
		return this.fraisTransport;
	}

	public void setFraisTransport(Float fraisTransport) {
		this.fraisTransport = fraisTransport;
	}

	@Column(name = "mnt_debours_transit")
	public Integer getMntDeboursTransit() {
		return this.mntDeboursTransit;
	}

	public void setMntDeboursTransit(Integer mntDeboursTransit) {
		this.mntDeboursTransit = mntDeboursTransit;
	}

	@Column(name = "taux_debours_transit", precision = 12, scale = 0)
	public Float getTauxDeboursTransit() {
		return this.tauxDeboursTransit;
	}

	public void setTauxDeboursTransit(Float tauxDeboursTransit) {
		this.tauxDeboursTransit = tauxDeboursTransit;
	}

	@Column(name = "prefixe_num_cdc")
	public Integer getPrefixeNumCdc() {
		return this.prefixeNumCdc;
	}

	public void setPrefixeNumCdc(Integer prefixeNumCdc) {
		this.prefixeNumCdc = prefixeNumCdc;
	}

	@Column(name = "poids_theorique")
	public Integer getPoidsTheorique() {
		return this.poidsTheorique;
	}

	public void setPoidsTheorique(Integer poidsTheorique) {
		this.poidsTheorique = poidsTheorique;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<ContratAchat> getContratAchats() {
		return this.contratAchats;
	}

	public void setContratAchats(Set<ContratAchat> contratAchats) {
		this.contratAchats = contratAchats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Analyse> getAnalyses() {
		return this.analyses;
	}

	public void setAnalyses(Set<Analyse> analyses) {
		this.analyses = analyses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<ReceptionProduits> getReceptionProduitses() {
		return this.receptionProduitses;
	}

	public void setReceptionProduitses(Set<ReceptionProduits> receptionProduitses) {
		this.receptionProduitses = receptionProduitses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<ContratVente> getContratVentes() {
		return this.contratVentes;
	}

	public void setContratVentes(Set<ContratVente> contratVentes) {
		this.contratVentes = contratVentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Variete> getVarietes() {
		return this.varietes;
	}

	public void setVarietes(Set<Variete> varietes) {
		this.varietes = varietes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Marque> getMarques() {
		return this.marques;
	}

	public void setMarques(Set<Marque> marques) {
		this.marques = marques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Qualite> getQualites() {
		return this.qualites;
	}

	public void setQualites(Set<Qualite> qualites) {
		this.qualites = qualites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<ItemsDebours> getItemsDebourses() {
		return this.itemsDebourses;
	}

	public void setItemsDebourses(Set<ItemsDebours> itemsDebourses) {
		this.itemsDebourses = itemsDebourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<FabricationLots> getFabricationLotses() {
		return this.fabricationLotses;
	}

	public void setFabricationLotses(Set<FabricationLots> fabricationLotses) {
		this.fabricationLotses = fabricationLotses;
	}

}
