package com.socodd.entities;
// Generated 2 août 2018 19:58:35 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "db_socodd")
public class Produit implements java.io.Serializable {

	private Integer id;
	private TypeSac typeSacBySacBrousse;
	private TypeSac typeSacBySacExport;
	private String code;
	private String nom;
	private String titreCompagne;
	private int prefNumBE;
	private int prochainAchatNum;
	private int cpteAchat;
	private float tauxAchatBic;
	private int prefNumBS;
	private int prochainVenteNum;
	private int cpteVte;
	private int cpteVenteBic;
	private float prixAchatIndicatif;
	private float prixVenteIndicatif;
	private float fraisTransport;
	private int mntDeboursTransit;
	private float tauxDeboursTransit;
	private int prefixeNumCdc;
	private int poidsTherorique;

	public Produit() {
	}

	public Produit(TypeSac typeSacBySacBrousse, TypeSac typeSacBySacExport, String code, String nom, String titreCompagne,
			int prefNumBE, int prochainAchatNum, int cpteAchat, float tauxAchatBic, int prefNumBS, int prochainVenteNum,
			int cpteVte, int cpteVenteBic, float prixAchatIndicatif, float prixVenteIndicatif, float fraisTransport,
			int mntDeboursTransit, float tauxDeboursTransit, int prefixeNumCdc, int poidsTherorique) {
		this.typeSacBySacBrousse = typeSacBySacBrousse;
		this.typeSacBySacExport = typeSacBySacExport;
		this.code = code;
		this.nom = nom;
		this.titreCompagne = titreCompagne;
		this.prefNumBE = prefNumBE;
		this.prochainAchatNum = prochainAchatNum;
		this.cpteAchat = cpteAchat;
		this.tauxAchatBic = tauxAchatBic;
		this.prefNumBS = prefNumBS;
		this.prochainVenteNum = prochainVenteNum;
		this.cpteVte = cpteVte;
		this.cpteVenteBic = cpteVenteBic;
		this.prixAchatIndicatif = prixAchatIndicatif;
		this.prixVenteIndicatif = prixVenteIndicatif;
		this.fraisTransport = fraisTransport;
		this.mntDeboursTransit = mntDeboursTransit;
		this.tauxDeboursTransit = tauxDeboursTransit;
		this.prefixeNumCdc = prefixeNumCdc;
		this.poidsTherorique = poidsTherorique;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sac_brousse", nullable = false)
	public TypeSac getTypeSacBySacBrousse() {
		return this.typeSacBySacBrousse;
	}

	public void setTypeSacBySacBrousse(TypeSac typeSacBySacBrousse) {
		this.typeSacBySacBrousse = typeSacBySacBrousse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sac_export", nullable = false)
	public TypeSac getTypeSacBySacExport() {
		return this.typeSacBySacExport;
	}

	public void setTypeSacBySacExport(TypeSac typeSacBySacExport) {
		this.typeSacBySacExport = typeSacBySacExport;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "titre_compagne", nullable = false)
	public String getTitreCompagne() {
		return this.titreCompagne;
	}

	public void setTitreCompagne(String titreCompagne) {
		this.titreCompagne = titreCompagne;
	}

	@Column(name = "pref_num_b_e", nullable = false)
	public int getPrefNumBE() {
		return this.prefNumBE;
	}

	public void setPrefNumBE(int prefNumBE) {
		this.prefNumBE = prefNumBE;
	}

	@Column(name = "prochain_achat_num", nullable = false)
	public int getProchainAchatNum() {
		return this.prochainAchatNum;
	}

	public void setProchainAchatNum(int prochainAchatNum) {
		this.prochainAchatNum = prochainAchatNum;
	}

	@Column(name = "cpte_achat", nullable = false)
	public int getCpteAchat() {
		return this.cpteAchat;
	}

	public void setCpteAchat(int cpteAchat) {
		this.cpteAchat = cpteAchat;
	}

	@Column(name = "taux_achat_bic", nullable = false, precision = 12, scale = 0)
	public float getTauxAchatBic() {
		return this.tauxAchatBic;
	}

	public void setTauxAchatBic(float tauxAchatBic) {
		this.tauxAchatBic = tauxAchatBic;
	}

	@Column(name = "pref_num_b_s", nullable = false)
	public int getPrefNumBS() {
		return this.prefNumBS;
	}

	public void setPrefNumBS(int prefNumBS) {
		this.prefNumBS = prefNumBS;
	}

	@Column(name = "prochain_vente_num", nullable = false)
	public int getProchainVenteNum() {
		return this.prochainVenteNum;
	}

	public void setProchainVenteNum(int prochainVenteNum) {
		this.prochainVenteNum = prochainVenteNum;
	}

	@Column(name = "cpte_vte", nullable = false)
	public int getCpteVte() {
		return this.cpteVte;
	}

	public void setCpteVte(int cpteVte) {
		this.cpteVte = cpteVte;
	}

	@Column(name = "cpte_vente_bic", nullable = false)
	public int getCpteVenteBic() {
		return this.cpteVenteBic;
	}

	public void setCpteVenteBic(int cpteVenteBic) {
		this.cpteVenteBic = cpteVenteBic;
	}

	@Column(name = "prix_achat_indicatif", nullable = false, precision = 12, scale = 0)
	public float getPrixAchatIndicatif() {
		return this.prixAchatIndicatif;
	}

	public void setPrixAchatIndicatif(float prixAchatIndicatif) {
		this.prixAchatIndicatif = prixAchatIndicatif;
	}

	@Column(name = "prix_vente_indicatif", nullable = false, precision = 12, scale = 0)
	public float getPrixVenteIndicatif() {
		return this.prixVenteIndicatif;
	}

	public void setPrixVenteIndicatif(float prixVenteIndicatif) {
		this.prixVenteIndicatif = prixVenteIndicatif;
	}

	@Column(name = "frais_transport", nullable = false, precision = 12, scale = 0)
	public float getFraisTransport() {
		return this.fraisTransport;
	}

	public void setFraisTransport(float fraisTransport) {
		this.fraisTransport = fraisTransport;
	}

	@Column(name = "mnt_debours_transit", nullable = false)
	public int getMntDeboursTransit() {
		return this.mntDeboursTransit;
	}

	public void setMntDeboursTransit(int mntDeboursTransit) {
		this.mntDeboursTransit = mntDeboursTransit;
	}

	@Column(name = "taux_debours_transit", nullable = false, precision = 12, scale = 0)
	public float getTauxDeboursTransit() {
		return this.tauxDeboursTransit;
	}

	public void setTauxDeboursTransit(float tauxDeboursTransit) {
		this.tauxDeboursTransit = tauxDeboursTransit;
	}

	@Column(name = "prefixe_num_cdc", nullable = false)
	public int getPrefixeNumCdc() {
		return this.prefixeNumCdc;
	}

	public void setPrefixeNumCdc(int prefixeNumCdc) {
		this.prefixeNumCdc = prefixeNumCdc;
	}

	@Column(name = "poids_therorique", nullable = false)
	public int getPoidsTherorique() {
		return this.poidsTherorique;
	}

	public void setPoidsTherorique(int poidsTherorique) {
		this.poidsTherorique = poidsTherorique;
	}

}
