package com.socodd.entities;
// Generated 21 juil. 2018 07:15:20 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Societe generated by hbm2java
 */
@Entity
@Table(name = "societe", catalog = "db_socodd")
public class Societe implements java.io.Serializable {

	private Integer id;
	private String code;
	private String raisonSociale;
	private String adresse;
	private String activite;
	private String pays;
	private String ville;
	private String telephone;
	private String fax;
	private String siteWeb;
	private String email;
	private String codeFiscal;
	private String agrement;
	private String compteContrib;
	private String codeImpExp;

	public Societe() {
	}

	public Societe(String code, String raisonSociale, String adresse, String activite, String pays, String ville,
			String telephone, String fax, String siteWeb, String email, String codeFiscal, String agrement,
			String compteContrib, String codeImpExp) {
		this.code = code;
		this.raisonSociale = raisonSociale;
		this.adresse = adresse;
		this.activite = activite;
		this.pays = pays;
		this.ville = ville;
		this.telephone = telephone;
		this.fax = fax;
		this.siteWeb = siteWeb;
		this.email = email;
		this.codeFiscal = codeFiscal;
		this.agrement = agrement;
		this.compteContrib = compteContrib;
		this.codeImpExp = codeImpExp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "raison_sociale", nullable = false, length = 50)
	public String getRaisonSociale() {
		return this.raisonSociale;
	}

	public void setRaisonSociale(String raisonSociale) {
		this.raisonSociale = raisonSociale;
	}

	@Column(name = "adresse", nullable = false, length = 65535)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "activite", nullable = false, length = 50)
	public String getActivite() {
		return this.activite;
	}

	public void setActivite(String activite) {
		this.activite = activite;
	}

	@Column(name = "pays", nullable = false, length = 50)
	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	@Column(name = "ville", nullable = false, length = 50)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "telephone", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax", nullable = false, length = 10)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "site_web", nullable = false, length = 50)
	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "code_fiscal", nullable = false, length = 50)
	public String getCodeFiscal() {
		return this.codeFiscal;
	}

	public void setCodeFiscal(String codeFiscal) {
		this.codeFiscal = codeFiscal;
	}

	@Column(name = "agrement", nullable = false, length = 50)
	public String getAgrement() {
		return this.agrement;
	}

	public void setAgrement(String agrement) {
		this.agrement = agrement;
	}

	@Column(name = "compte_contrib", nullable = false, length = 50)
	public String getCompteContrib() {
		return this.compteContrib;
	}

	public void setCompteContrib(String compteContrib) {
		this.compteContrib = compteContrib;
	}

	@Column(name = "code_imp_exp", nullable = false, length = 50)
	public String getCodeImpExp() {
		return this.codeImpExp;
	}

	public void setCodeImpExp(String codeImpExp) {
		this.codeImpExp = codeImpExp;
	}

}
