package com.socodd.entities;
// Generated 21 juil. 2018 07:15:20 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SousPrefecture generated by hbm2java
 */
@Entity
@Table(name = "sous_prefecture", catalog = "db_socodd")
public class SousPrefecture implements java.io.Serializable {

	private Integer id;
	private String code;
	private String nom;
	private int prefecture;
	private float longitude;
	private float latitude;
	private Set<Route> routes = new HashSet<Route>(0);

	public SousPrefecture() {
	}

	public SousPrefecture(String code, String nom, int prefecture, float longitude, float latitude) {
		this.code = code;
		this.nom = nom;
		this.prefecture = prefecture;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public SousPrefecture(String code, String nom, int prefecture, float longitude, float latitude, Set<Route> routes) {
		this.code = code;
		this.nom = nom;
		this.prefecture = prefecture;
		this.longitude = longitude;
		this.latitude = latitude;
		this.routes = routes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prefecture", nullable = false)
	public int getPrefecture() {
		return this.prefecture;
	}

	public void setPrefecture(int prefecture) {
		this.prefecture = prefecture;
	}

	@Column(name = "longitude", nullable = false, precision = 12, scale = 0)
	public float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(float longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", nullable = false, precision = 12, scale = 0)
	public float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(float latitude) {
		this.latitude = latitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sousPrefecture")
	public Set<Route> getRoutes() {
		return this.routes;
	}

	public void setRoutes(Set<Route> routes) {
		this.routes = routes;
	}

}
