package com.socodd.entities;
// Generated 30 juil. 2018 14:57:08 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TypeContrat generated by hbm2java
 */
@Entity
@Table(name = "type_contrat", catalog = "db_socodd")
public class TypeContrat implements java.io.Serializable {

	private Integer id;
	private String code;
	private String nom;
	private float nom2;

	public TypeContrat() {
	}

	public TypeContrat(String code, String nom, float nom2) {
		this.code = code;
		this.nom = nom;
		this.nom2 = nom2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "nom2", nullable = false, precision = 12, scale = 0)
	public float getNom2() {
		return this.nom2;
	}

	public void setNom2(float nom2) {
		this.nom2 = nom2;
	}

}
