package com.socodd.entities;
// Generated 21 juil. 2018 07:15:20 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TypeSac generated by hbm2java
 */
@Entity
@Table(name = "type_sac", catalog = "db_socodd")
public class TypeSac implements java.io.Serializable {

	private Integer id;
	private int code;
	private int nom;
	private float tare;
	private int stockDernierInventaire;
	private Date date;
	private int stockDisponible;

	public TypeSac() {
	}

	public TypeSac(int code, int nom, float tare, int stockDernierInventaire, Date date, int stockDisponible) {
		this.code = code;
		this.nom = nom;
		this.tare = tare;
		this.stockDernierInventaire = stockDernierInventaire;
		this.date = date;
		this.stockDisponible = stockDisponible;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false)
	public int getNom() {
		return this.nom;
	}

	public void setNom(int nom) {
		this.nom = nom;
	}

	@Column(name = "tare", nullable = false, precision = 12, scale = 0)
	public float getTare() {
		return this.tare;
	}

	public void setTare(float tare) {
		this.tare = tare;
	}

	@Column(name = "stock_dernier_inventaire", nullable = false)
	public int getStockDernierInventaire() {
		return this.stockDernierInventaire;
	}

	public void setStockDernierInventaire(int stockDernierInventaire) {
		this.stockDernierInventaire = stockDernierInventaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "stock_disponible", nullable = false)
	public int getStockDisponible() {
		return this.stockDisponible;
	}

	public void setStockDisponible(int stockDisponible) {
		this.stockDisponible = stockDisponible;
	}

}
