package com.socodd.entities;
// Generated 25 août 2018 14:31:28 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TypeSac generated by hbm2java
 */
@Entity
@Table(name = "type_sac", catalog = "db_socodd")
public class TypeSac implements java.io.Serializable {

	private Integer id;
	private String code;
	private String nom;
	private float tare;
	private int stockDernierInventaire;
	private Date date;
	private int stockDisponible;
	private Set<ReceptionProduits> receptionProduitses = new HashSet<ReceptionProduits>(0);
	private Set<Produit> produitsForSacBrousse = new HashSet<Produit>(0);
	private Set<Produit> produitsForSacExport = new HashSet<Produit>(0);

	public TypeSac() {
	}

	public TypeSac(String code, String nom, float tare, int stockDernierInventaire, Date date, int stockDisponible) {
		this.code = code;
		this.nom = nom;
		this.tare = tare;
		this.stockDernierInventaire = stockDernierInventaire;
		this.date = date;
		this.stockDisponible = stockDisponible;
	}

	public TypeSac(String code, String nom, float tare, int stockDernierInventaire, Date date, int stockDisponible,
			Set<ReceptionProduits> receptionProduitses, Set<Produit> produitsForSacBrousse,
			Set<Produit> produitsForSacExport) {
		this.code = code;
		this.nom = nom;
		this.tare = tare;
		this.stockDernierInventaire = stockDernierInventaire;
		this.date = date;
		this.stockDisponible = stockDisponible;
		this.receptionProduitses = receptionProduitses;
		this.produitsForSacBrousse = produitsForSacBrousse;
		this.produitsForSacExport = produitsForSacExport;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "tare", nullable = false, precision = 12, scale = 0)
	public float getTare() {
		return this.tare;
	}

	public void setTare(float tare) {
		this.tare = tare;
	}

	@Column(name = "stock_dernier_inventaire", nullable = false)
	public int getStockDernierInventaire() {
		return this.stockDernierInventaire;
	}

	public void setStockDernierInventaire(int stockDernierInventaire) {
		this.stockDernierInventaire = stockDernierInventaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "stock_disponible", nullable = false)
	public int getStockDisponible() {
		return this.stockDisponible;
	}

	public void setStockDisponible(int stockDisponible) {
		this.stockDisponible = stockDisponible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeSac")
	public Set<ReceptionProduits> getReceptionProduitses() {
		return this.receptionProduitses;
	}

	public void setReceptionProduitses(Set<ReceptionProduits> receptionProduitses) {
		this.receptionProduitses = receptionProduitses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeSacBySacBrousse")
	public Set<Produit> getProduitsForSacBrousse() {
		return this.produitsForSacBrousse;
	}

	public void setProduitsForSacBrousse(Set<Produit> produitsForSacBrousse) {
		this.produitsForSacBrousse = produitsForSacBrousse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeSacBySacExport")
	public Set<Produit> getProduitsForSacExport() {
		return this.produitsForSacExport;
	}

	public void setProduitsForSacExport(Set<Produit> produitsForSacExport) {
		this.produitsForSacExport = produitsForSacExport;
	}

}
