package com.socodd.entities;
// Generated 21 juil. 2018 07:15:20 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "db_socodd")
public class Utilisateur implements java.io.Serializable {

	private Integer id;
	private ProfileUtilisateur profileUtilisateur;
	private String code;
	private String prenom;
	private String nom;
	private String matricule;
	private String fonction;
	private String email;
	private String cel;
	private String telephone;
	private String motPasse;

	public Utilisateur() {
	}

	public Utilisateur(ProfileUtilisateur profileUtilisateur, String code, String prenom, String nom, String matricule,
			String fonction, String email, String cel, String telephone, String motPasse) {
		this.profileUtilisateur = profileUtilisateur;
		this.code = code;
		this.prenom = prenom;
		this.nom = nom;
		this.matricule = matricule;
		this.fonction = fonction;
		this.email = email;
		this.cel = cel;
		this.telephone = telephone;
		this.motPasse = motPasse;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profile", nullable = false)
	public ProfileUtilisateur getProfileUtilisateur() {
		return this.profileUtilisateur;
	}

	public void setProfileUtilisateur(ProfileUtilisateur profileUtilisateur) {
		this.profileUtilisateur = profileUtilisateur;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "matricule", nullable = false, length = 50)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "fonction", nullable = false, length = 50)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "cel", nullable = false, length = 10)
	public String getCel() {
		return this.cel;
	}

	public void setCel(String cel) {
		this.cel = cel;
	}

	@Column(name = "telephone", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "mot_passe", nullable = false, length = 50)
	public String getMotPasse() {
		return this.motPasse;
	}

	public void setMotPasse(String motPasse) {
		this.motPasse = motPasse;
	}

}
