package com.socodd.entities;
// Generated 21 juil. 2018 07:15:20 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Variete generated by hbm2java
 */
@Entity
@Table(name = "variete", catalog = "db_socodd")
public class Variete implements java.io.Serializable {

	private Integer id;
	private String code;
	private int produit;
	private String nom;
	private String abrege;
	private int ordre;

	public Variete() {
	}

	public Variete(String code, int produit, String nom, String abrege, int ordre) {
		this.code = code;
		this.produit = produit;
		this.nom = nom;
		this.abrege = abrege;
		this.ordre = ordre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "produit", nullable = false)
	public int getProduit() {
		return this.produit;
	}

	public void setProduit(int produit) {
		this.produit = produit;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "abrege", nullable = false, length = 20)
	public String getAbrege() {
		return this.abrege;
	}

	public void setAbrege(String abrege) {
		this.abrege = abrege;
	}

	@Column(name = "ordre", nullable = false)
	public int getOrdre() {
		return this.ordre;
	}

	public void setOrdre(int ordre) {
		this.ordre = ordre;
	}

}
