package com.socodd.entities;
// Generated 30 juil. 2018 14:57:08 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Variete generated by hbm2java
 */
@Entity
@Table(name = "variete", catalog = "db_socodd")
public class Variete implements java.io.Serializable {

	private Integer id;
	private Produit produit;
	private String code;
	private String nom;
	private String abrege;
	private int ordre;
	private Set<ReceptionProduits> receptionProduitses = new HashSet<ReceptionProduits>(0);

	public Variete() {
	}

	public Variete(Produit produit, String code, String nom, String abrege, int ordre) {
		this.produit = produit;
		this.code = code;
		this.nom = nom;
		this.abrege = abrege;
		this.ordre = ordre;
	}

	public Variete(Produit produit, String code, String nom, String abrege, int ordre,
			Set<ReceptionProduits> receptionProduitses) {
		this.produit = produit;
		this.code = code;
		this.nom = nom;
		this.abrege = abrege;
		this.ordre = ordre;
		this.receptionProduitses = receptionProduitses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "produit", nullable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "abrege", nullable = false, length = 20)
	public String getAbrege() {
		return this.abrege;
	}

	public void setAbrege(String abrege) {
		this.abrege = abrege;
	}

	@Column(name = "ordre", nullable = false)
	public int getOrdre() {
		return this.ordre;
	}

	public void setOrdre(int ordre) {
		this.ordre = ordre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "variete")
	public Set<ReceptionProduits> getReceptionProduitses() {
		return this.receptionProduitses;
	}

	public void setReceptionProduitses(Set<ReceptionProduits> receptionProduitses) {
		this.receptionProduitses = receptionProduitses;
	}

}
